### PR TITLE
Fix comments starting with # are deprecated

### PR DESCRIPTION
**Pull request by umpirsky**
Fixes the build.

### CODE REVIEW

**Comment by umpirsky** [comment]
@makasim Can we tag some minor release after this?

**Comment by makasim** [comment]
I'll do it tomorrow

**Comment by umpirsky** [comment]
@makasim Thanks, please ping when you release it.

**Comment by makasim** [comment]
@umpirsky released https://github.com/Payum/Payum/releases/tag/1.3.9

**Comment by umpirsky** [comment]
Thanks @makasim! Really appreciate the speed.  :+1:

**Pull request merged**
