### PR TITLE
Use the CSPRNG provided by PHP 7

### PR DESCRIPTION
**Pull request by paragonie-scott**
For PHP 5 support, see: https://github.com/paragonie/random_compat

### CODE REVIEW

**Comment by makasim** [comment]
Is it available since PHP7.0? The payum lib is PHP 7.0+.

**Comment by paragonie-scott** [comment]
Yep! PHP 7.0 is when `random_bytes()` landed.

**Comment by paragonie-scott** [comment]
Is there anything I can help with to unstick this pull request?

**Review by pierredup — APPROVED** [review]

**Comment by pierredup** [comment]
Thank you @paragonie-scott

**Pull request merged**
