### PR TITLE
Fix stripe CreateCustomer extension

### PR DESCRIPTION
**Pull request by gpou**

### CODE REVIEW

**Comment by makasim** [comment]
👍 Could you add a test?

**Comment by gpou** [comment]
@makasim Sure, I will.
In fact, I created the pull request by mistake before finishing the work. :)

**Comment by makasim** [comment]
In any case the change make sense to me.

**Comment by gpou** [comment]
@makasim We are adding several features to the Stripe module.
I close this PR, and once we finish, we'll make a bigger one with everything.

**Pull request closed without merging**
