### PR TITLE
Add property to class GetHttpRequest

### PR DESCRIPTION
**Pull request by ibogdan94**
Based on the code, where you use this class, you forgot to add the variable headers

### CODE REVIEW

**Comment by makasim** [comment]
what headers do you exactly need?

**Comment by ibogdan94** [comment]
Maxim, Payum\Core\Bridge\Symfony\Action\GetHttpRequestAction.php
Function updateRequest takes parameters GetHttpRequest $request, Request $httpRequest
Than you use properties form class GetHttpRequest.php, but property headers doesn't described in it

**Comment by makasim** [comment]
What header do you need but it missed right now?

**Comment by ibogdan94** [comment]
I don't need a header. I thought it would be logical to add a property to the class that you used in your code, but forgot to add in GetHttpRequest.php

**Comment by makasim** [comment]
I did not forget. It was done on purpose.

**Pull request closed without merging**
