### PR TITLE
* Add skeleton code for canceling recurring payments

### PR DESCRIPTION
**Pull request by alexandernst**
* Use generic Cancel request class
* Reuse manageRecurringPaymentsProfileStatus code
* Add unit tests

### CODE REVIEW

**Comment by makasim** [comment]
you have to add `CancelRecurringPaymentsProfileAction ` to a payment factory.

**Comment by alexandernst** [comment]
@makasim Done :)

**Comment by makasim** [comment]
are you sure?

**Comment by alexandernst** [comment]
Doh, what about now? @makasim

**Comment by makasim** [comment]
You did it! Thanks.

**Comment by makasim** [comment]
I'll add a short doc and release it asap.

**Comment by alexandernst** [comment]
\o/ yay!!! Thank you!

**Pull request merged**
