### PR TITLE
feat: support-symfony-6, except for symfony/http-foundation

### PR DESCRIPTION
**Pull request by Chris53897**
getMasterRequest() is removed in Symfony 6.
https://github.com/symfony/http-foundation/blob/6.0/CHANGELOG.md#60

This PR builds a small BC layer to support symfony 4-6.

PhpUnit needs to be allow 9.5 otherwise tests will fail. This is because of the mocking of Symfony/Form and more.
`Error : Call to undefined method ReflectionUnionType::getName() /Payum/src/Payum/Core/Tests/Bridge/Symfony/Action/ObtainCreditCardActionTest.php:383
 /Payum/src/Payum/Core/Tests/Bridge/Symfony/Action/ObtainCreditCardActionTest.php:83`

The symfony/http-foundation in version 6 is excluded because of https://github.com/Payum/Payum/issues/933

### CODE REVIEW

**Comment by Chris53897** [comment]
Test fail again because of PhpUnit 9 deprecation `at()`

**Comment by pierredup** [comment]
@Chris53897 I have switched the branch to 1.x, since this is a new feature that should go into the next minor 1 release (The branch 1.7.x is for bug-fixes against the 1.7 version only).

> Test fail again because of PhpUnit 9 deprecation at()

Is phpunit 9 necessary for this change? Otherwise it can be removed, I'll work on a separate PR to support PhpUnit 9 then

**Comment by Chris53897** [comment]
ok, thanks.

Yes PhpUnit 9 is necessary, otherwise tests will fail for symfony 6. See ErrorMessage above.
For 2.x the work is already done.
An improvment could be to rewrite the tests for the `->at() `Deprecations.
But this has no priority in my eyes for the moment.

**Comment by pierredup** [comment]
> For 2.x the work is already done.
> An improvment could be to rewrite the tests for the ->at() Deprecations.
> But this has no priority in my eyes for the moment.

I'll work on removing the `at calls, and will merge the changes into your PR at #932. That way, we can get the build green for that PR. I'll also change the target to `1.x`, since it's something that can be merged into the next minor release for version 1, and will help with other changes going forward (E.G this PR)

**Comment by Chris53897** [comment]
Sounds good. Thanks

I target the wrong branch again. Shame on me. Sorry

**Comment by pierredup** [comment]
Thank you @Chris53897

**Pull request merged**
