### PR TITLE
Improve serialize / unserialize when using FilesystemStrorage

### PR DESCRIPTION
**Pull request by daveli**
I encountered an issue when dealing with serialize and unserialize some "unsafe" (", ', :, or ; in the) data. This patch will fix that.

### CODE REVIEW

**Comment by makasim** [comment]
What was the problem?

**Comment by makasim** [comment]
FYI: you should not use this store in prod.

**Comment by makasim** [comment]
Its goal to allow you easily and quickly start with Payum ,you  have to replace it with something else ASAP.

**Comment by daveli** [comment]
This is pure a patch for testing purposes. I just happen to ran into it and it was a quick fix. I'm using a model at this very moment.

**Comment by makasim** [comment]
What did you get, an exception or error, corrupted data?

**Comment by makasim** [comment]
The fix should be done in no BC break way. which is not how it is right now.

**Comment by daveli** [comment]
Typical corrupted data with serialize: Error at offset x of x byte in file x.php

**Pull request closed without merging**
