### PR TITLE
fixed usage of PENDINGREASON (paymentinfo instead of paymentrequest)

### PR DESCRIPTION
**Pull request by toooni**
@makasim As you can see here (https://developer.paypal.com/docs/classic/api/merchant/DoCapture_API_Operation_NVP/) PENDINGREASON is a Payment Info field, not a Payment Request field. Capturing an authorized payment does not work at the moment.

### CODE REVIEW

**Comment by makasim** [comment]
I suspect this also fixes https://github.com/Payum/PayumBundle/issues/360

**Comment by makasim** [comment]
Thanks

**Comment by toooni** [comment]
@makasim do you know how long it takes until this change is on the subtree split? btw. why is the architecture like this? it's very complicated to contribute for me :( (maybe I just don't get it)

**Comment by makasim** [comment]
I do split manually, usually while releasing a new version. run it now should be ok in few minutes.

**Comment by toooni** [comment]
@makasim sorry to bother you, https://github.com/Payum/PaypalExpressCheckoutNvp is still not up to date.
Are you sure you want to keep it like that? It might be a bit discouraging to people wanting to contribute.

**Comment by makasim** [comment]
done https://github.com/Payum/PaypalExpressCheckoutNvp/commits/master

**Comment by makasim** [comment]
@toooni do you have an idea how it could be improved? 
Having stuff in one place makes my life a lot easier

**Comment by makasim** [comment]
And this is like symfony does.

**Comment by toooni** [comment]
@makasim hmm.. i just realized that it might be very hard to maintain all the payment "plugins" and it's versions for you.
Maybe the thing you could do is having a link on top of the subtree split repositories to an explanation how to create a PR from a branch of a subtree split.

**Comment by makasim** [comment]
@toooni Available since 1.3.1

**Comment by makasim** [comment]
@toooni https://github.com/Payum/Payum/pull/527. I havent tested it yet but something like this might works

**Comment by toooni** [comment]
@makasim great 🎉  I'll test it soon..

**Pull request merged**
