### PR TITLE
chore: add ci tests for php 8.2, bump github actions versions

### PR DESCRIPTION
**Pull request by Chris53897**

### CODE REVIEW

**Comment by Chris53897** [comment]
Good job from the what-the-diff bot.

**Comment by Chris53897** [comment]
@pierredup Can you please have a look at this? My main goal is to find deprecations and check if it is ready for php 8.3.

**Comment by pierredup** [comment]
I'm recreating the PR, I was trying to rebase it against 1.7.x so that we can get the PHP 8.2 support into 1.7, but totally messed up the branch. Will recreate the PR against 1.7.x with only the necessary chanegs

**Comment by pierredup** [comment]
#964

**Comment by Chris53897** [comment]
ok, thanks for explonation

**Pull request closed without merging**
