### PR TITLE
Update obtain_checkout_token.html.twig

### PR DESCRIPTION
**Pull request by Perfect-Web**
should take into account the cents

### CODE REVIEW

**Comment by makasim** [comment]
You have to set correct price

**Comment by Perfect-Web** [comment]
i have set the correct price, but if i set the amount = $1000 on stripe is registered as $100.00
See http://stackoverflow.com/questions/25546372/stripe-payment-gateway-i-wants-to-use-amount-in-decimal-format

**Comment by makasim** [comment]
I mean when you create payment details you have to pass it in cents (actually in format specific to a gateway you selected).

**Comment by makasim** [comment]
Payum does not normalize data in any way (in case you dont use Order and FillOrderDetailsAction).

**Comment by makasim** [comment]
see https://github.com/Payum/PayumBundle/blob/master/Resources/doc/custom_purchase_examples/stripe_js.md

there is an example of 1 USD purchase

**Comment by Perfect-Web** [comment]
i figured that out, but when it is saved thru doctrine in db it will be saved as 100 not 1

**Comment by makasim** [comment]
> i figured that out, but when it is saved thru doctrine in db it will be saved as 100 not 1

yes you are right

**Comment by Perfect-Web** [comment]
so what do you suggest, cause as it is right now is very confusing ...

**Comment by makasim** [comment]
what is confusing?

**Comment by Perfect-Web** [comment]
that you set the amount you wanna charge to 100 times more than you wanna charge, and if you dont make any transformations when the process is done to the final amount, you will end up giving your clients 100 times more credit than you suppose to

**Comment by makasim** [comment]
you have to store your price somewhere else in your own format, payment details is a payment gateway specific format and vary a lot, so do not use them directly,

**Pull request closed without merging**
