### PR TITLE
[sofort] Add ability to disable notifications.

### PR DESCRIPTION
**Pull request by makasim**
fixes https://github.com/Payum/Payum/issues/628

### CODE REVIEW

**Comment by makasim** [comment]
@blubberblah could you be able to test it?

**Comment by blubberblah** [comment]
Not yet, but I'll have a look into it...
cheers

**Comment by blubberblah** [comment]
Could you please tell me how I get your changes via composer to my local installation so I can test? We are using SVN at work and I'm not familiar with the whole Git/Github thing ;-)

**Comment by makasim** [comment]
@benbender basically you have to add my repository to your composer.json file like

```json
{
    "repositories": [
        {
            "type": "git",
            "url": "git@github.com:makasim/Payum.git"
        }
}
```

and change `payum/payum` requirment to be `dev-sofort-disable-notification-url`. Do `composer update payum/payum`. 

That's it.

https://getcomposer.org/doc/05-repositories.md#repository

**Comment by blubberblah** [comment]
Ok, I can confirm that your changes are functional! notification_url gets omitted when disable_notification is set to true. Thank you for the help, cheers!

**Comment by makasim** [comment]
@blubberblah  Thanks for your help. gonna merge

**Pull request merged**
