### PR TITLE
Update supported-gateways.md

### PR DESCRIPTION
**Pull request by fullpipe**
Add Uniteller and Flexidengi payment gateways

### CODE REVIEW

**Comment by makasim** [comment]
Great! Thanks!

One suggestion so far. You can reuse [unsafe notify action](https://github.com/Payum/PayumBundle/blob/master/Controller/NotifyController.php#L10). And implement the logic like this  https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/PayumBundle/Payum/Be2bill/Action/NotifyAction.php

**Comment by makasim** [comment]
Also you can add an extension which looks for notify requests with expected model and checks its status. if status is success you dispatch an event. If you dont want bother with it you can use build it extension: https://github.com/Payum/Payum/blob/master/src/Payum/Core/Bridge/Symfony/Extension/EventDispatcherExtension.php

**Comment by makasim** [comment]
Or like this https://github.com/Payum/Payum/pull/408

**Comment by fullpipe** [comment]
@makasim what do you think about adding `StorageAwareInterface` for actions just like `ApiAwareInterface`. For example for `GetPaymentFromHttpRequestRequest($_REQUEST)` 

And add something like `GatewayRequestGueser::getGateway($_REQUEST)` for using with unsafe notifications to identify gateway from request params.

**Comment by makasim** [comment]
@fullpipe  Not sure it has to be in the lib itself, Rare case, only few gateways does not support notify url per payment and also it is easy to implement.

**Pull request merged**
