### PR TITLE
Add EventDispatcherExtension doc

### PR DESCRIPTION
**Pull request by davidfuhr**

### CODE REVIEW

**Comment by makasim** [comment]
Would be good to add a section how to configure it in symfony app.

**Comment by davidfuhr** [comment]
Shouldn't PayumBundle specific stuff go to PayumBundle documentation?

**Comment by makasim** [comment]
This is about few lines of doc and could be placed here. If the doc grows we can add a dedicated chapter in the bundle. There is no any special rules, if you think it should be in the bundle, I am fine with it too.

**Comment by makasim** [comment]
Thanks

**Pull request merged**
