### PR TITLE
Update payum/core dependency

### PR DESCRIPTION
**Pull request by RealAestan**
Following this : https://github.com/Payum/PayumBundle/pull/519 update dependency to allow compatibility with newer versions of softwares. @Tetragramat

### CODE REVIEW

**Comment by Tetragramat** [comment]
I don't see any need to change `payum/core` deps in each gateway. Could you explain why it is needed?

**Comment by RealAestan** [comment]
@Tetragramat To be able to install payum/stripe for example, in a symfony 5 project with payum/payum-bundle. Or it will be in conflicts (see https://github.com/Payum/PayumBundle/pull/519). Or the only way would be to install all gateways with payum/payum.

**Comment by Tetragramat** [comment]
Could you make bug report with your project's composer require and result of your composer update?

**Comment by RealAestan** [comment]
I made it work with the following composer settings : 
        "payum/core": "dev-master as 1.6",
        "payum/payum-bundle": "dev-master",
        "payum/stripe": "^1.5",
I'm closing this PR.

**Pull request closed without merging**
